package rudok.action.error;

public enum ErrorEnum {
    AUTHOR,
    ADD_CHILDREN_TO_SLIDE,
    EMPTY_STRING_AUTHOR,
    NOTHING_SELECTED,
    DELETE_WORKSPACE,
    BACKGROUND_NOT_IMAGE,
    NO_PRESENTATION_NO_STATE,
    BACKGROUND_NOT_PRESENTATION,
    NOT_PRESENTATION,
    NOT_IMAGE;
}
